# Generated by Django 4.1.4 on 2023-05-03 08:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloger_bio', models.TextField(blank=True, help_text='Write about yourself', max_length=500)),
                ('genre', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], default='U', help_text='Your Genre', max_length=1)),
                ('bloger_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Come up with a title', max_length=200)),
                ('post_date', models.DateTimeField(default=datetime.datetime(2023, 5, 3, 15, 44, 28, 121635), editable=False, max_length=50)),
                ('description', models.TextField(help_text='Write your post here', max_length=200000)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='NBlog.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(default='03/05/2023 15:44:28', max_length=50)),
                ('comment', models.TextField(help_text='Write your comment', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NBlog.bloger')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBlog.post')),
            ],
        ),
    ]
