# Generated by Django 4.1.4 on 2023-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBlog', '0006_alter_comment_post_date_alter_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='date_of_birth',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default='2023-07-05 16:20:19', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default='2023-07-05 16:20:19', editable=False, max_length=50),
        ),
    ]
