# Generated by Django 4.1.4 on 2023-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBlog', '0007_bloger_date_of_birth_alter_comment_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='date_of_birth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default='2023-07-05 16:21:10', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default='2023-07-05 16:21:10', editable=False, max_length=50),
        ),
    ]
