# Generated by Django 4.1.4 on 2023-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBlog', '0011_alter_bloger_bloger_bio_alter_comment_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default='2023-09-05 22:14:15', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Write your post here', max_length=200000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default='2023-09-05 22:14:15', editable=False, max_length=50),
        ),
    ]
