# Generated by Django 4.1.4 on 2023-05-12 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBlog', '0014_alter_comment_post_date_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 15, 15, 12, 58681), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 15, 15, 12, 58681), max_length=50),
        ),
    ]
