# Generated by Django 4.1.4 on 2023-05-16 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBlog', '0015_alter_bloger_image_alter_comment_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 16, 9, 57, 798078), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 16, 9, 57, 797076), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Come up with a title', max_length=200),
        ),
    ]
