# Generated by Django 4.1.4 on 2023-05-23 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBlog', '0016_alter_bloger_image_alter_comment_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 21, 39, 33, 967013), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 21, 39, 33, 966013), max_length=50),
        ),
    ]
